"""Build independent v1/v2 seed-0 comparison after the probe has completed."""
import hashlib,json
from pathlib import Path
from methods.project_paths import project_root
R=project_root(); V1=R/'results/experiments/mlp/weibo/formal/seed_0/metrics.json'; P=R/'results/experiments/mlp/weibo/protocol_v2_class_weight_probe'; v1=json.loads(V1.read_text());v2=json.loads((P/'seed_0/metrics.json').read_text()); pre=json.loads((P/'seed_0/preflight.json').read_text()); audit=json.loads((R/'audit/mlp_v1_recompute.json').read_text()); v1test=next(r for r in audit['runs'] if r['seed']==0)['splits']['test_mask']
diff={'v1_seed_0':'results/experiments/mlp/weibo/formal/seed_0/metrics.json','v2_seed_0':'results/experiments/mlp/weibo/protocol_v2_class_weight_probe/seed_0/metrics.json','only_config_difference':'class_weight','v1_class_weight':'none','v2_class_weight':[v2['class_weight_normal'],v2['class_weight_anomaly']],'shared_input_sha256':pre['input_sha256'],'shared_code_sha256':pre['code_sha256'],'shared_environment':pre['environment'],'v1':{k:v1[k] for k in ['f1_macro','auroc','best_epoch','threshold']},'v2':{k:v2[k] for k in ['f1_macro','auroc','best_epoch','threshold','test_predicted_anomaly_count','test_predicted_anomaly_ratio','test_confusion_matrix_labels_0_1','auroc_score']},'delta':{'f1_macro':v2['f1_macro']-v1['f1_macro'],'auroc':v2['auroc']-v1['auroc']},'conclusion':'类别权重的单变量影响；不构成论文级复现成功声明。'}
(P/'config_diff.json').write_text(json.dumps(diff,indent=2)); lines=['# MLP Weibo v1 vs protocol_v2 class-weight probe','','**Conclusion: 类别权重的单变量影响。** This is not a paper-level reproduction-success claim.','', '| Item | v1 seed=0 | v2 seed=0 |','| --- | ---: | ---: |']
for k in ['f1_macro','auroc','best_epoch','threshold']:lines.append(f'| {k} | {v1[k]} | {v2[k]} |')
lines += [f"| test predicted anomalies | {sum(v1test['confusion_matrix_labels_0_1'][i][1] for i in (0,1))} ({v1test['predicted_anomaly_ratio']:.10f}) | {v2['test_predicted_anomaly_count']} ({v2['test_predicted_anomaly_ratio']:.10f}) |",f"| test confusion matrix labels [0,1] | `{v1test['confusion_matrix_labels_0_1']}` | `{v2['test_confusion_matrix_labels_0_1']}` |",f"| AUROC score | softmax(logits)[:,1] (v1 audit) | {v2['auroc_score']} |",'', '## Exact config diff','', '- The run-before-training config-diff assertion passed only if all semantic fields other than class weight were identical.', '- The sole training/configuration difference is `CrossEntropyLoss(weight=[1.0, train_normal_count/train_anomaly_count])` in v2.',f"- v2 train counts: normal={v2['train_normal_count']}, anomaly={v2['train_anomaly_count']}; weights=[{v2['class_weight_normal']}, {v2['class_weight_anomaly']}].",f"- Class-weight source: {v2['class_weight_source']}",'- It does not prove this was HSMAD authors\' Table 1 MLP configuration.','', '## Shared frozen evidence','',f"- input/mask SHA256: `{json.dumps(pre['input_sha256'],sort_keys=True)}`",f"- code SHA256: `{json.dumps(pre['code_sha256'],sort_keys=True)}`",f"- environment: `{json.dumps(pre['environment'],sort_keys=True)}`",f"- F1 delta: {diff['delta']['f1_macro']:+.10f}; AUROC delta: {diff['delta']['auroc']:+.10f}",'']
(P/'comparison.md').write_text('\n'.join(lines));print(json.dumps(diff))
