"""Build independent v1/v2/v3 seed-0 dropout probe comparison; no training."""
import json
from pathlib import Path
from methods.project_paths import project_root
R=project_root();v1=json.loads((R/'results/experiments/mlp/weibo/formal/seed_0/metrics.json').read_text());v2=json.loads((R/'results/experiments/mlp/weibo/protocol_v2_class_weight_probe/seed_0/metrics.json').read_text());P=R/'results/experiments/mlp/weibo/protocol_v3_dropout_zero_probe';v3=json.loads((P/'seed_0/metrics.json').read_text());audit=json.loads((R/'audit/mlp_v1_recompute.json').read_text());v1test=next(x for x in audit['runs'] if x['seed']==0)['splits']['test_mask'];pre=json.loads((P/'seed_0/preflight.json').read_text())
rows=[('v1 formal',v1,0.5,'none',{'n':sum(v1test['confusion_matrix_labels_0_1'][i][1] for i in (0,1)),'r':v1test['predicted_anomaly_ratio'],'cm':v1test['confusion_matrix_labels_0_1']}),('v2 class_weight',v2,0.5,f"[1.0, {v2['class_weight_anomaly']}]",{'n':v2['test_predicted_anomaly_count'],'r':v2['test_predicted_anomaly_ratio'],'cm':v2['test_confusion_matrix_labels_0_1']}),('v3 dropout_zero',v3,0.0,'none',{'n':v3['test_predicted_anomaly_count'],'r':v3['test_predicted_anomaly_ratio'],'cm':v3['test_confusion_matrix_labels_0_1']})]
data={'conclusion':'dropout 的单变量影响；不构成论文级复现成功声明。','paper':{'f1_macro':0.9223,'auroc':0.9801},'shared_v1_v3_evidence':pre,'rows':[]}
for name,m,d,w,t in rows:data['rows'].append({'protocol':name,'f1_macro':m['f1_macro'],'auroc':m['auroc'],'best_epoch':m['best_epoch'],'threshold':m['threshold'],'test_predicted_anomalies':t['n'],'test_predicted_anomaly_ratio':t['r'],'test_confusion_matrix_labels_0_1':t['cm'],'class_weight':w,'dropout':d,'delta_paper_f1':m['f1_macro']-.9223,'delta_paper_auroc':m['auroc']-.9801})
(P/'comparison.json').write_text(json.dumps(data,indent=2));lines=['# MLP Weibo seed=0: v1 / v2 / v3 comparison','','**Conclusion: dropout 的单变量影响。** This is not a paper-level reproduction-success claim.','', '| Protocol | F1-Macro | AUROC | best_epoch | threshold | test predicted anomalies | class_weight | dropout | ΔF1 vs paper | ΔAUROC vs paper |','| --- | ---: | ---: | ---: | ---: | --- | --- | ---: | ---: | ---: |']
for x in data['rows']:lines.append(f"| {x['protocol']} | {x['f1_macro']:.10f} | {x['auroc']:.10f} | {x['best_epoch']} | {x['threshold']:.2f} | {x['test_predicted_anomalies']} ({x['test_predicted_anomaly_ratio']:.10f}) | {x['class_weight']} | {x['dropout']:.1f} | {x['delta_paper_f1']:+.10f} | {x['delta_paper_auroc']:+.10f} |")
lines+=['','## Test confusion matrices (labels [0,1])','']
for x in data['rows']:lines += [f"- {x['protocol']}: `{x['test_confusion_matrix_labels_0_1']}`"]
lines+=['','## v1 vs v3 preflight assertion','','- Only semantic difference: `dropout: 0.5 -> 0.0`.','- Both v1 and v3 use `class_weight=none`.','- Shared input/mask SHA256, code SHA256, reference, and environment are in `seed_0/preflight.json`.','- AUROC for all rows is anomaly score `softmax(logits)[:,1]`.','']
(P/'comparison.md').write_text('\n'.join(lines));print(json.dumps(data))
